### ISSUE TITLE
NetworkingDsc\NetAdapterBinding continually correcting when executed via Puppet

### ISSUE THREAD

**Issue by joeypiccola** [puppetlabs/ruby-pwsh#106] opened 2021-02-06 00:02 UTC
## Describe the Bug
The following resource continually disables ipv6. 

```ruby
# https://github.com/dsccommunity/NetworkingDsc/wiki/NetAdapterBinding
dsc_netadapterbinding { 'disable_ipv6':
  dsc_interfacealias => '*',
  dsc_componentid    => 'ms_tcpip6',
  dsc_state          => 'Disabled',
}
```

Puppet run output.

```plaintext
Notice: /Stage[main]/Domaincontroller_win::System/Dsc_netadapterbinding[disable_ipv6]/dsc_state: dsc_state changed 'Enabled' to 'Disabled' (corrective)
Notice: dsc_netadapterbinding[{:name=>"disable_ipv6", :dsc_interfacealias=>"*", :dsc_componentid=>"ms_tcpip6"}]: Updating: Finished in 1.18 seconds
```

When debugging this and breaking out the `get` method we see the current state is stored in the property `currentstate` and not `state`. 

```powershell
$InvokeParams = @{
    Name = 'NetAdapterBinding'; 
    Method = 'get'; 
    Property = @{
        interfacealias = '*'; 
        componentid = 'ms_tcpip6'
    }; 
    ModuleName = @{
        ModuleName = 'C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/networkingdsc/dsc_resources/NetworkingDsc/NetworkingDsc.psd1'; 
        RequiredVersion = '8.2.0'
    }
}
Invoke-DscResource @InvokeParams -Verbose
```

```plaintext
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourceget,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SEA1W3MORPH81 with user sid S-1-5-removed.
VERBOSE: [node]:                            [[NetAdapterBinding]DirectResourceAccess] Get-TargetResource: Getting the '*' Inerface 'ms_tcpip6' Binding.
VERBOSE: [node]: LCM:  [ End    Get      ]  [[NetAdapterBinding]DirectResourceAccess]  in 1.4530 seconds.
VERBOSE: [node]: LCM:  [ End    Set      ]    in  2.5940 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.


ConfigurationName    : 
DependsOn            : 
ModuleName           : C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/networkingdsc/dsc_resources/NetworkingDsc/NetworkingDsc.psd1
ModuleVersion        : 8.2.0
PsDscRunAsCredential : 
ResourceId           : 
SourceInfo           : 
ComponentId          : ms_tcpip6
CurrentState         : Disabled
InterfaceAlias       : *
State                : Enabled
PSComputerName       : localhost

VERBOSE: Time taken for configuration job to complete is 2.819 seconds
```

When debugging this and breaking out the `test` method we see `InDesiredState` as `true`. Despite `InDesiredState` being `true` Puppet continually `set`s the NetAdapterBinding resource.

```powershell
$InvokeParams = @{
    Name = 'NetAdapterBinding'; 
    Method = 'test'; 
    Property = @{
        interfacealias = '*'; 
        componentid = 'ms_tcpip6'
        state = 'disabled'
    }; 
    ModuleName = @{
        ModuleName = 'C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/networkingdsc/dsc_resources/NetworkingDsc/NetworkingDsc.psd1'; 
        RequiredVersion = '8.2.0'
    }
}
Invoke-DscResource @InvokeParams -Verbose
```

```plaintext
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SEA1W3MORPH81 with user sid S-1-5-removed.
VERBOSE: [node]: LCM:  [ Start  Test     ]  [[NetAdapterBinding]DirectResourceAccess]
VERBOSE: [node]:                            [[NetAdapterBinding]DirectResourceAccess] Test-TargetResource: Checking the '*' Inerface 'ms_tcpip6' Binding.
VERBOSE: [node]:                            [[NetAdapterBinding]DirectResourceAccess] Test-TargetResource: '*' Inerface 'ms_tcpip6' Binding is in desired state.
VERBOSE: [node]: LCM:  [ End    Test     ]  [[NetAdapterBinding]DirectResourceAccess] True in 1.3280 seconds.
VERBOSE: [node]: LCM:  [ End    Set      ]    in  2.4690 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.

InDesiredState 
-------------- 
True           
VERBOSE: Time taken for configuration job to complete is 2.673 seconds
```

## Expected Behavior
I'd expect that when `test` is run and returns `InDesiredState` as `true` that Puppet not run `set` on the NetAdapterBinding resource.

## Steps to Reproduce
Using the modules below and the `dsc_netadapterbinding` resource above this issue can be reproduced. 

## Environment
This is with Puppet Enterprise v2019.7.0 using the following modules. 

```ini
mod 'dsc-activedirectorydsc', '6.0.1-0-2'
mod 'dsc-networkingdsc', '8.2.0-0-1'
```

## Additional Context
End to end testing outside of Puppet.

```powershell
Configuration BuildTest01 {
    Import-DscResource -Module 'C:\ProgramData\PuppetLabs\puppet\cache\lib\puppet_x\networkingdsc\dsc_resources\NetworkingDsc\NetworkingDsc.psd1'
    Node $AllNodes.NodeName {
        NetAdapterBinding DisableIPv6
        {
            InterfaceAlias = '*'
            ComponentId    = 'ms_tcpip6'
            State          = 'Disabled'
        }
    }
}

$ConfigData = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
        }
    )
}

BuildTest01 -ConfigurationData $ConfigData
Start-DscConfiguration -Wait -Path .\BuildTest01 -Verbose -Force -ComputerName localhost
```

```plaintext
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SEA1W3MORPH81 with user sid S-1-5-removed.
VERBOSE: [node]: LCM:  [ Start  Set      ]
VERBOSE: [node]: LCM:  [ Start  Resource ]  [[NetAdapterBinding]DisableIPv6]
VERBOSE: [node]: LCM:  [ Start  Test     ]  [[NetAdapterBinding]DisableIPv6]
VERBOSE: [node]:                            [[NetAdapterBinding]DisableIPv6] Test-TargetResource: Checking the '*' Inerface 'ms_tcpip6' Binding.
VERBOSE: [node]:                            [[NetAdapterBinding]DisableIPv6] Test-TargetResource: '*' Inerface 'ms_tcpip6' Binding is in desired state.
VERBOSE: [node]: LCM:  [ End    Test     ]  [[NetAdapterBinding]DisableIPv6]  in 0.1100 seconds.
VERBOSE: [node]: LCM:  [ Skip   Set      ]  [[NetAdapterBinding]DisableIPv6]
VERBOSE: [node]: LCM:  [ End    Resource ]  [[NetAdapterBinding]DisableIPv6]
VERBOSE: [node]: LCM:  [ End    Set      ]
VERBOSE: [node]: LCM:  [ End    Set      ]    in  0.2030 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.313 seconds
```

**Comment by michaeltlombardi** [comment] 2021-02-09 01:45
@joeypiccola digging into this a little bit (sorry for the delay!) and I think the problem is twofold:

1. The Resource has an ... interesting design which has `CurrentState` as a separate read only property from `State` which it _always_ returns as whatever you specify to it. I'm not _sure_ on this - we'll need to file an issue upstream on it - but I think that `State` should return the value currently being returned by `CurrentState`. This whole design is a little confusing to me, tbh - the same check is made in `Test-TargetResource` to compare to specified state. Unfortunately, fixing this will be a breaking change (theoretically?) for the resource. As it is, `State` will always return `Enabled` because of the current implementation (we only pass mandatory properties to the `Get` request because that's all we know for sure ahead of time it will take).
2. Puppet actually does not utilize the `Test` method for `Invoke-DscResource` at all - it runs `Get`, compares the returned structure to that specified in the manifest, and then _if_ things are out of sync, it provides property by property reporting of what is being changed during the Puppet run.

The root problem isn't that Puppet is mistakenly applying `Set` after `Test` comes back in sync but rather that the resource as currently written is not canonicalizable and comparable - it does not return an object which can be meaningfully compared during the Puppet run.

**Comment by michaeltlombardi** [comment] 2021-02-11 18:00
Closing this as an issue with the upstream resource.

**Closed by michaeltlombardi** 2021-02-11 18:00 UTC
Labels: bug
