### ISSUE TITLE
ActiveDirectoryDsc: dscADGroup option non-idempotent

### ISSUE THREAD

**Issue by eebuta** [puppetlabs/ruby-pwsh#83] opened 2021-01-08 09:01 UTC
## Describe the Bug
Hi All, I am using the MSFT_ADGroup resource in activedirectorydsc (https://forge.puppet.com/modules/dsc/activedirectorydsc) module to create a new group in AD. The module runs successfully on the first try, then throws errors on the sequential runs. I think this happens because the AD group is configured as required, however the activedirectorydsc module might not be in a position to handle errors regarding the existing objects. What’s the best way to resolve the following issue?

####Output

1st run
```
PS C:\> puppet agent -t
[mNotice: Local environment: 'production' doesn't match server specified node environment 'development', switching agent to 'development'.[0m
[0;32mInfo: Retrieving pluginfacts[0m
[0;32mInfo: Retrieving plugin[0m
[0;32mInfo: Retrieving locales[0m
[0;32mInfo: Loading facts[0m
[0;32mInfo: Caching catalog for 122uks0806.uk.deloitte.com[0m
[0;32mInfo: Applying configuration version '058UKP02057-development-7bf907e2c4f'[0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_description: dsc_description changed  to 'Create AD Group for Host/Machine'[0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_displayname: dsc_displayname changed  to 'ServerAdmin-test04'[0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_ensure: dsc_ensure changed 'Absent' to 'Present'[0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_members: dsc_members changed [] to ['Mgmt access'][0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_category: dsc_category changed  to 'Security'[0m
[mNotice: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]/dsc_path: dsc_path changed  to 'OU=AWS,OU=Cloud services,OU=Local Server Access,OU=Groups,OU=UK,DC=uk,DC=testdomain,DC=com'[0m
[mNotice: dsc_adgroup[{:name=>"ServerAdmin-Group", :dsc_groupname=>"ServerAdmin-test04"}]: Creating: Finished in 1.61 seconds[0m
[mNotice: Applied catalog in 5.07 seconds[0m
```
2nd run - Failed
```
PS C:\> puppet agent -t
[mNotice: Local environment: 'production' doesn't match server specified node environment 'development', switching agent to 'development'.[0m
[0;32mInfo: Retrieving pluginfacts[0m
[0;32mInfo: Retrieving plugin[0m
[0;32mInfo: Retrieving locales[0m
[0;32mInfo: Loading facts[0m
puppet : [1;31mError: dsc_adgroup: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from 
ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK 
documentation and inspect the server trace logs.[0m
At line:1 char:1
+ puppet agent -t
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([1;31mError: d...trace logs.[0m:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[0;32mInfo: Caching catalog for 122uks0806.uk.deloitte.com[0m
[0;32mInfo: Applying configuration version '058UKP02057-development-7bf907e2c4f'[0m
[1;31mError: dsc_adgroup: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or 
from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server 
trace logs.[0m
[1;31mError: /Stage[main]/Profile::Baseline::Common::Domainjoin/Dsc_adgroup[ServerAdmin-Group]: Could not evaluate: undefined method `[]' for nil:NilClass[0m
[mNotice: Applied catalog in 3.61 seconds[0m 
```
## Expected Behavior
Expected Puppet.Dsc to run without failure on other attempts

## Steps to Reproduce

Please see manifest used to reproduce the issue 
```
# A description of what this class does
#
# @example
#   include profile::baseline::common::domainjoin
class profile::baseline::common::domainjoin (
  String $machine_ou,
  String $joinuser,
  String $joinpassword,
  String $joindomain  = 'uk.testdomain.com',
  Array $arrcertname  = split($trusted['certname'], '[.]'),
  Array $groups = ['Mgmt access']
) {
  case $facts['osfamily'] {
    default: {}
    'windows': {
      dsc_adgroup { 'ServerAdmin-Group':
        dsc_description => 'Create AD Group for Host/Machine',
        dsc_groupname   => 'ServerAdmin-test04',
        dsc_category    => 'Security',
        dsc_path        => 'OU=AWS,OU=Cloud services,OU=Local Server Access,OU=Groups,OU=UK,DC=uk,DC=testdomain,DC=com',
        dsc_ensure      => 'Present',
        dsc_displayname => 'ServerAdmin-test04',
        dsc_members     => $groups,
        dsc_credential  => {
            'user'     => $joinuser,
            'password' => Sensitive($joinpassword),
        }
      }
    }
  }
}
```

## Environment
OsName : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture : 64-bit
WindowsBuildLabEx : 14393.3471.amd64fre.rs1_release_1.191218-1729
OsLanguage : en-US
OsMuiLanguages : {en-US

## Additional Context

Version of the forge module that was used
https://forge.puppet.com/modules/dsc/activedirectorydsc - 6.0.1-0-1

**Comment by michaeltlombardi** [comment] 2021-01-11 14:55
Closing this as a duplicate of puppetlabs/puppet.dsc#112

**Closed by michaeltlombardi** 2021-01-11 14:55 UTC
Labels: bug
